import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useState } from "react";
import { Alert, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { useAppLanguage } from "@/lib/i18n";
import { useRecorder } from "@/lib/recorder-context";
import type { RecorderSettings } from "@/shared/recorder-types";

const sampleRates = [16000, 22050, 44100, 48000];
const bitRates = [64000, 96000, 128000, 192000];

export default function SettingsScreen() {
  const { settings, updateSettings } = useRecorder();
  const { language } = useAppLanguage();
  const [draft, setDraft] = useState<RecorderSettings>(settings);
  const zh = language === "zh";
  const copy = zh ? {
    title: "录音设置", subtitle: "控制音频质量与录制前后的静音时长", audio: "音频参数", sample: "采样率", sampleHint: "影响音频细节与文件体积", bit: "比特率", bitHint: "AAC 编码目标码率", channels: "声道", channelsHint: "单人采音通常选择单声道", mono: "单声道", stereo: "立体声", silence: "静音控制", leading: "首端静音", leadingHint: "点击开始后，在正式录制前预留的安静时长", trailing: "尾端静音", trailingHint: "点击停止后，在保存文件前保留的安静时长", milliseconds: "毫秒", note: "静音时长可设为 0–10000 毫秒。录音文件使用 AAC/M4A 保存，并按发音人和任务归档。", save: "保存录音设置", saved: "设置已保存", savedHint: "新的录音参数会在下一句开始录制时生效。",
  } : {
    title: "Recording settings", subtitle: "Control audio quality and leading or trailing silence.", audio: "Audio parameters", sample: "Sample rate", sampleHint: "Controls audio detail and file size", bit: "Bit rate", bitHint: "Target AAC encoding rate", channels: "Channels", channelsHint: "Mono is usually best for a single speaker", mono: "Mono", stereo: "Stereo", silence: "Silence controls", leading: "Leading silence", leadingHint: "Quiet time before the recording starts", trailing: "Trailing silence", trailingHint: "Quiet time retained before the file is saved", milliseconds: "ms", note: "Silence can be 0–10000 ms. Audio is saved as AAC/M4A and grouped by speaker and task.", save: "Save recording settings", saved: "Settings saved", savedHint: "New parameters apply when the next sentence starts recording.",
  };
  const save = () => { const leading = Math.max(0, Math.min(10000, Number(draft.leadingSilenceMs) || 0)); const trailing = Math.max(0, Math.min(10000, Number(draft.trailingSilenceMs) || 0)); updateSettings({ ...draft, leadingSilenceMs: leading, trailingSilenceMs: trailing }); setDraft({ ...draft, leadingSilenceMs: leading, trailingSilenceMs: trailing }); Alert.alert(copy.saved, copy.savedHint); };
  return <ScreenContainer className="px-5" edges={["top", "left", "right"]}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><Text style={styles.title}>{copy.title}</Text><Text style={styles.subtitle}>{copy.subtitle}</Text><Text style={styles.section}>{copy.audio}</Text><View style={styles.card}><OptionRow title={copy.sample} helper={copy.sampleHint} options={sampleRates} value={draft.sampleRate} unit="Hz" onChange={(sampleRate) => setDraft((current) => ({ ...current, sampleRate }))} /><Divider /><OptionRow title={copy.bit} helper={copy.bitHint} options={bitRates} value={draft.bitRate} unit="kbps" formatter={(value) => value / 1000} onChange={(bitRate) => setDraft((current) => ({ ...current, bitRate }))} /><Divider /><Text style={styles.optionTitle}>{copy.channels}</Text><Text style={styles.optionHelper}>{copy.channelsHint}</Text><View style={styles.segment}>{[1, 2].map((channels) => <TouchableOpacity key={channels} style={[styles.segmentItem, draft.channels === channels && styles.segmentSelected]} onPress={() => setDraft((current) => ({ ...current, channels: channels as 1 | 2 }))}><Text style={[styles.segmentText, draft.channels === channels && styles.segmentTextSelected]}>{channels === 1 ? copy.mono : copy.stereo}</Text></TouchableOpacity>)}</View></View><Text style={styles.section}>{copy.silence}</Text><View style={styles.card}><Text style={styles.optionTitle}>{copy.leading}</Text><Text style={styles.optionHelper}>{copy.leadingHint}</Text><NumberInput value={draft.leadingSilenceMs} unit={copy.milliseconds} onChange={(leadingSilenceMs) => setDraft((current) => ({ ...current, leadingSilenceMs }))} /><Divider /><Text style={styles.optionTitle}>{copy.trailing}</Text><Text style={styles.optionHelper}>{copy.trailingHint}</Text><NumberInput value={draft.trailingSilenceMs} unit={copy.milliseconds} onChange={(trailingSilenceMs) => setDraft((current) => ({ ...current, trailingSilenceMs }))} /></View><View style={styles.note}><MaterialIcons color="#2F4DA0" name="info-outline" size={19} /><Text style={styles.noteText}>{copy.note}</Text></View><TouchableOpacity style={styles.saveButton} onPress={save}><Text style={styles.saveText}>{copy.save}</Text></TouchableOpacity></ScrollView></ScreenContainer>;
}

const Divider = () => <View style={styles.divider} />;
function OptionRow({ title, helper, options, value, unit, formatter = (number: number) => number, onChange }: { title: string; helper: string; options: number[]; value: number; unit: string; formatter?: (value: number) => number; onChange: (value: number) => void }) { return <View><Text style={styles.optionTitle}>{title}</Text><Text style={styles.optionHelper}>{helper}</Text><View style={styles.chips}>{options.map((option) => <TouchableOpacity key={option} style={[styles.chip, value === option && styles.chipActive]} onPress={() => onChange(option)}><Text style={[styles.chipText, value === option && styles.chipTextActive]}>{formatter(option)} {unit}</Text></TouchableOpacity>)}</View></View>; }
function NumberInput({ value, unit, onChange }: { value: number; unit: string; onChange: (value: number) => void }) { return <View style={styles.numberRow}><TextInput value={String(value)} keyboardType="number-pad" onChangeText={(text) => onChange(Number(text.replace(/[^0-9]/g, "")) || 0)} style={styles.numberInput} /><Text style={styles.unit}>{unit}</Text></View>; }

const styles = StyleSheet.create({ content: { paddingBottom: 32, paddingTop: 10 }, title: { color: "#182033", fontSize: 29, fontWeight: "800", letterSpacing: -0.5 }, subtitle: { color: "#65708A", fontSize: 14, marginTop: 6 }, section: { color: "#3F4A62", fontSize: 14, fontWeight: "800", letterSpacing: 0.3, marginBottom: 9, marginTop: 25 }, card: { backgroundColor: "#FFFFFF", borderColor: "#E4E8F0", borderRadius: 18, borderWidth: 1, padding: 17 }, optionTitle: { color: "#182033", fontSize: 16, fontWeight: "800" }, optionHelper: { color: "#65708A", fontSize: 13, lineHeight: 19, marginTop: 4 }, chips: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 14 }, chip: { backgroundColor: "#F2F4F8", borderRadius: 10, paddingHorizontal: 11, paddingVertical: 9 }, chipActive: { backgroundColor: "#E7EEFF", borderColor: "#2F4DA0", borderWidth: 1 }, chipText: { color: "#59647B", fontSize: 13, fontWeight: "700" }, chipTextActive: { color: "#2F4DA0" }, divider: { backgroundColor: "#E8EBF3", height: 1, marginVertical: 18 }, segment: { backgroundColor: "#EEF1F7", borderRadius: 11, flexDirection: "row", marginTop: 14, padding: 3 }, segmentItem: { alignItems: "center", borderRadius: 8, flex: 1, paddingVertical: 10 }, segmentSelected: { backgroundColor: "#FFFFFF" }, segmentText: { color: "#65708A", fontSize: 14, fontWeight: "700" }, segmentTextSelected: { color: "#2F4DA0" }, numberRow: { alignItems: "center", flexDirection: "row", gap: 10, marginTop: 13 }, numberInput: { backgroundColor: "#F2F4F8", borderRadius: 10, color: "#182033", fontSize: 16, fontWeight: "700", paddingHorizontal: 13, paddingVertical: 10, width: 110 }, unit: { color: "#65708A", fontSize: 14 }, note: { alignItems: "flex-start", backgroundColor: "#EAF0FF", borderRadius: 14, flexDirection: "row", gap: 10, marginTop: 20, padding: 14 }, noteText: { color: "#415273", flex: 1, fontSize: 13, lineHeight: 20 }, saveButton: { alignItems: "center", backgroundColor: "#2F4DA0", borderRadius: 16, marginTop: 22, paddingVertical: 16 }, saveText: { color: "#FFFFFF", fontSize: 16, fontWeight: "800" } });
