import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useState } from "react";
import { Alert, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { useRecorder } from "@/lib/recorder-context";
import type { RecorderSettings } from "@/shared/recorder-types";
const sampleRates = [16000, 22050, 44100, 48000]; const bitRates = [64000, 96000, 128000, 192000];
export default function SettingsScreen() { const { settings, updateSettings } = useRecorder(); const [draft, setDraft] = useState<RecorderSettings>(settings); const save = () => { const leading = Math.max(0, Math.min(10000, Number(draft.leadingSilenceMs) || 0)); const trailing = Math.max(0, Math.min(10000, Number(draft.trailingSilenceMs) || 0)); updateSettings({ ...draft, leadingSilenceMs: leading, trailingSilenceMs: trailing }); setDraft({ ...draft, leadingSilenceMs: leading, trailingSilenceMs: trailing }); Alert.alert("设置已保存", "新的录音参数会在下一句开始录制时生效。"); }; return <ScreenContainer className="px-5" edges={["top", "left", "right"]}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><Text style={styles.title}>录音设置</Text><Text style={styles.subtitle}>控制音频质量与录制前后的静音时长</Text><Text style={styles.section}>音频参数</Text><View style={styles.card}><OptionRow title="采样率" helper="影响音频细节与文件体积" options={sampleRates} value={draft.sampleRate} unit="Hz" onChange={(sampleRate) => setDraft((current) => ({ ...current, sampleRate }))} /><Divider /><OptionRow title="比特率" helper="AAC 编码目标码率" options={bitRates} value={draft.bitRate} unit="kbps" formatter={(value) => value / 1000} onChange={(bitRate) => setDraft((current) => ({ ...current, bitRate }))} /><Divider /><Text style={styles.optionTitle}>声道</Text><Text style={styles.optionHelper}>单人采音通常选择单声道</Text><View style={styles.segment}>{[1, 2].map((channels) => <TouchableOpacity key={channels} style={[styles.segmentItem, draft.channels === channels && styles.segmentSelected]} onPress={() => setDraft((current) => ({ ...current, channels: channels as 1 | 2 }))}><Text style={[styles.segmentText, draft.channels === channels && styles.segmentTextSelected]}>{channels === 1 ? "单声道" : "立体声"}</Text></TouchableOpacity>)}</View></View><Text style={styles.section}>静音控制</Text><View style={styles.card}><Text style={styles.optionTitle}>首端静音</Text><Text style={styles.optionHelper}>点击开始后，在正式录制前预留的安静时长</Text><NumberInput value={draft.leadingSilenceMs} onChange={(leadingSilenceMs) => setDraft((current) => ({ ...current, leadingSilenceMs }))} /><Divider /><Text style={styles.optionTitle}>尾端静音</Text><Text style={styles.optionHelper}>点击停止后，在保存文件前保留的安静时长</Text><NumberInput value={draft.trailingSilenceMs} onChange={(trailingSilenceMs) => setDraft((current) => ({ ...current, trailingSilenceMs }))} /></View><View style={styles.note}><MaterialIcons color="#2F4DA0" name="info-outline" size={19} /><Text style={styles.noteText}>静音时长可设为 0–10000 毫秒。录音文件使用 AAC/M4A 保存，并按发音人和任务归档。</Text></View><TouchableOpacity style={styles.saveButton} onPress={save}><Text style={styles.saveText}>保存录音设置</Text></TouchableOpacity></ScrollView></ScreenContainer>; }
const Divider = () => <View style={styles.divider} />;
function OptionRow({ title, helper, options, value, unit, formatter = (number: number) => number, onChange }: { title: string; helper: string; options: number[]; value: number; unit: string; formatter?: (value: number) => number; onChange: (value: number) => void }) { return <View><Text style={styles.optionTitle}>{title}</Text><Text style={styles.optionHelper}>{helper}</Text><View style={styles.chips}>{options.map((option) => <TouchableOpacity key={option} style={[styles.chip, value === option && styles.chipActive]} onPress={() => onChange(option)}><Text style={[styles.chipText, value === option && styles.chipTextActive]}>{formatter(option)} {unit}</Text></TouchableOpacity>)}</View></View>; }
const NumberInput = ({ value, onChange }: { value: number; onChange: (value: number) => void }) => <View style={styles.numberRow}><TextInput value={String(value)} keyboardType="number-pad" onChangeText={(text) => onChange(Number(text.replace(/[^0-9]/g, "")) || 0)} style={styles.numberInput} /><Text style={styles.unit}>毫秒</Text></View>;
const styles = StyleSheet.create({ content: { paddingBottom: 32, paddingTop: 10 }, title: { color: "#182033", fontSize: 29, fontWeight: "800", letterSpacing: -0.5 }, subtitle: { color: "#65708A", fontSize: 14, marginTop: 6 }, section: { color: "#3F4A62", fontSize: 14, fontWeight: "800", letterSpacing: 0.3, marginBottom: 9, marginTop: 25 }, card: { backgroundColor: "#FFFFFF", borderColor: "#E4E8F0", borderRadius: 18, borderWidth: 1, padding: 17 }, optionTitle: { color: "#182033", fontSize: 16, fontWeight: "800" }, optionHelper: { color: "#65708A", fontSize: 13, lineHeight: 19, marginTop: 4 }, chips: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 14 }, chip: { backgroundColor: "#F2F4F8", borderRadius: 10, paddingHorizontal: 11, paddingVertical: 9 }, chipActive: { backgroundColor: "#E7EEFF", borderColor: "#2F4DA0", borderWidth: 1 }, chipText: { color: "#59647B", fontSize: 13, fontWeight: "700" }, chipTextActive: { color: "#2F4DA0" }, divider: { backgroundColor: "#E8EBF3", height: 1, marginVertical: 18 }, segment: { backgroundColor: "#EEF1F7", borderRadius: 11, flexDirection: "row", marginTop: 14, padding: 3 }, segmentItem: { alignItems: "center", borderRadius: 8, flex: 1, paddingVertical: 10 }, segmentSelected: { backgroundColor: "#FFFFFF" }, segmentText: { color: "#65708A", fontSize: 14, fontWeight: "700" }, segmentTextSelected: { color: "#2F4DA0" }, numberRow: { alignItems: "center", flexDirection: "row", gap: 10, marginTop: 13 }, numberInput: { backgroundColor: "#F2F4F8", borderRadius: 10, color: "#182033", fontSize: 16, fontWeight: "700", paddingHorizontal: 13, paddingVertical: 10, width: 110 }, unit: { color: "#65708A", fontSize: 14 }, note: { alignItems: "flex-start", backgroundColor: "#EAF0FF", borderRadius: 14, flexDirection: "row", gap: 10, marginTop: 20, padding: 14 }, noteText: { color: "#415273", flex: 1, fontSize: 13, lineHeight: 20 }, saveButton: { alignItems: "center", backgroundColor: "#2F4DA0", borderRadius: 16, marginTop: 22, paddingVertical: 16 }, saveText: { color: "#FFFFFF", fontSize: 16, fontWeight: "800" } });
